name: CI
on:
  push:
    paths:
      - 'public/**'


jobs:
  deploy-to-webdav:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: push code
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.address}}
          webdav_username: ${{secrets.username}}
          webdav_password: ${{secrets.password}}
          webdav_upload_path: "www/"
          files: "./public/**"
