name: CI
on:
  push:
    paths:
      - 'public/**'


jobs:
  deploy-to-webdav:
    runs-on: ubuntu-latest
    steps:
      - name: push to webdav
        run: |
          curl --user '${{secrets.username}}:${{secrets.password}}' -T 'public/*' '${{secrets.address}}/www/'
